name: JMeter K8s Load Test

on:
  workflow_dispatch:
    inputs:
      jmx_file:
        description: 'JMX File ka naam (e.g., test.jmx)'
        required: true
        default: 'test.jmx'
      test_name:
        description: 'Test ka naam (S3 folder ke liye)'
        required: true
        default: 'LoadTest-1'
      worker_count:
        description: 'Worker Pods Needed'
        required: true
        default: '3'

jobs:
  run-load-test:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Grab Code
      uses: actions/checkout@v4

    - name: 2. AWS Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1

    - name: 3. K8s Path
      run: aws eks update-kubeconfig --name mera-jmeter-cluster --region ap-south-1

    - name: 4. Start Worker
      run: |
        sed -i "s/replicas: .*/replicas: ${{ github.event.inputs.worker_count }}/g" worker.yaml
        kubectl apply -f worker.yaml

    - name: 5. Master Command 
      run: |
        sleep 20 # Wait till workers are ready
        
        # 1. Find Worker IP Addresses
        WORKER_IPS=$(kubectl get pods -l jmeter-role=worker -o jsonpath='{.items[*].status.podIP}' | tr ' ' ',')
        
        # 2. Overwrite master.yaml
        sed -i "s/default.jmx/${{ github.event.inputs.jmx_file }}/g" master.yaml
        sed -i "s/LoadTest-1/${{ github.event.inputs.test_name }}/g" master.yaml
        sed -i "s/10.0.0.1,10.0.0.2/$WORKER_IPS/g" master.yaml
        
        # 3. Launch Master Pod
        kubectl apply -f master.yaml
